http_server:
  address: ":8080"
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 30s

grpc_client:
  address: "db-service:5050"
  timeout: 5s
  retries: 3

logger:
  level: "debug"
  format: "json"
  directory: "/app/logs"

kafka:
  broker_address: "kafka:9092"
  topic: "metrics"
  retries: 3
  timeout: 10s
  acks: "0"