{
 "title": "General Dashboard of HTTP stats",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total number of requests for last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of requests by handlers and statuses",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (path, method, status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Frequency of requests by handlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (path, method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}