grpc:
  port: 5050

postgres:
  host: storage
  port: 5432
  user: postgres
  password: password
  db_name: postgres

redis:
  host: cache
  port: 6379
  password: redis
  TTL: 120s

logger:
  level: debug
  format: json
  directory: /app/logs