grpc:
  port: 5050

postgres:                  # Конфиг PostgreSQL:
  host: storage            # Хост бд
  port: 5432               # Порт бд
  user: postgres           # Имя пользователя
  password: password       # Пароль пользователя
  db_name: postgres        # Имя бд

redis:
  host: cache
  port: 6379
  password: redis
  TTL: 120